[package]
name = "unco_derives"
edition = "2021"
version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0", features = ["derive", "fold", "full", "extra-traits"]}
quote = "1.0"
