[package]
name = "unco"
edition = "2021"
version = { workspace = true }

[dependencies]
anyhow = "1.0"
once_cell = "1.19"
serde = "1.0"
serde_json = "1.0"
surrealdb = "1.5"
tokio = "1.38"
unco_derives = {path = "../unco_derives"}